### ISSUE TITLE
Faltando campos no modelo de agendamento

### ISSUE THREAD

**Issue by evertondanda** [gbrlbarreto/projetomedical#14]
https://github.com/gbrlbarreto/projetomedical/blob/4620600d3fabc12ccc85d5a48b6250b5c461ddec/agendamentos/models.py#L12

No modelo de agendamentos, o ideal é sempre inserirmos alguns campos novos como: 

created_at timestamp not null default now(quando criado)
updated_at timestamp timestamp not null default now(quando alterado)
arquivado boolean not null default false

Para nos dar informações extras de data de criação e alteração do agendamento. Outro ponto importante é a deleção de itens, informações importantes como dados de atendimento ao cliente é interessante que se permaneçam na base. Portanto tratamos com um flag arquivado e nunca o deletamos. 

Falout tambem o id do modelo exposto na classe.

**Comment by gbrlbarreto** [comment]
Issue concluída na branch [15-lista](https://github.com/gbrlbarreto/projetomedical/tree/15-lista)
