### ISSUE TITLE
Estruturar pastas do rest_framework

### ISSUE THREAD

**Issue by evertonmedicalsys** [gbrlbarreto/projetomedical#27]
Separar as classes do rest_framework utilizadas para expor os recursos em pastas separadas.

Ex.:

```
recurso/api/
   - __init__.py
   - serializers.py
   - viewsets.py
   - urls.py 
```

**Comment by gbrlbarreto** [comment]
Estruturação resolvida - Concluído na branch [17-lista](https://github.com/gbrlbarreto/projetomedical/tree/17-lista)
